spring:
  profiles: dev
  datasource:
    driverClassName: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/db_springboot
    username: root
    password: Gfj123456
  jpa:
    hibernate.ddl-auto: update
    generate-ddl: true
    show-sql: true


---
spring:
  profiles: prod
  datasource:
    driverClassName: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/db_springboot_prod
    username: root
    password: Gfj123456
  jpa:
    hibernate.ddl-auto: update
    generate-ddl: true
    show-sql: true